[component]
structures = ["content_blocks"]
label = "Services"
description = "Services section"
icon = "build"
tags = []

[props]
preheading = "Our Services"
heading = "We provide a wide range of creative services "

[[props.sections]]
icon = "ti-desktop"
title = "Web development"
text = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-layers"
title = "Interface Design"
text = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-bar-chart"
title = "Business Consulting"
text = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-vector"
title = "Branding"
text = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-android"
title = "App development"
text = "A digital agency isn't here to replace your internal team, we're here to partner."

[[props.sections]]
icon = "ti-pencil-alt"
title = "Content creation"
text = "A digital agency isn't here to replace your internal team, we're here to partner."