[component]
structures = ["content_blocks"]
label = "Contact Form"
description = "Contact form section"
icon = "send_to_mobile"
tags = []

[props]
preheading = "We are Professionals"
heading = "Don’t Hesitate to contact with us for any kind of information"
form_heading = "Contact Form"
address = "North Main Street, Brooklyn, Australia"
email = "contact@mail.com"
phone = "+88 01672 506 744"
facebook = "themefisher"
twitter = "themefisher"
linkedin = "themefisher"
